#!/usr/bin/env bash
set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI is required: https://cli.github.com/"
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Run gh auth login before setting repository secrets."
  exit 1
fi

read -r -p "NBUNK_SECRET from 'nsyte ci' (must start with nbunksec1): " NBUNK_SECRET
read -r -p "Nostr relay URL for nsite deploy (for example wss://relay.nsite.lol): " NSYTE_RELAY
read -r -p "Blossom server URL (for example https://cdn.hzrd149.com): " BLOSSOM_SERVER_URL
read -r -p "Optional named nsite (press enter for root npub site): " NSITE_NAME

if [[ "$NBUNK_SECRET" != nbunksec1* ]]; then
  echo "NBUNK_SECRET must be the nbunksec1... credential generated by 'nsyte ci'."
  exit 1
fi

gh secret set NBUNK_SECRET --body "$NBUNK_SECRET"
gh secret set NSYTE_RELAY --body "$NSYTE_RELAY"
gh secret set BLOSSOM_SERVER_URL --body "$BLOSSOM_SERVER_URL"

if [[ -n "$NSITE_NAME" ]]; then
  gh secret set NSITE_NAME --body "$NSITE_NAME"
fi

echo "Repository secrets are configured for .github/workflows/deploy-nsite.yml"
