#!/usr/bin/env bash
set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI is required: https://cli.github.com/"
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Run gh auth login before setting repository secrets."
  exit 1
fi

read -r -p "NBUNK_SECRET from 'nsyte ci' (must start with nbunksec1): " NBUNK_SECRET
read -r -p "Nostr relay URLs for nsite deploy, comma-separated (for example wss://relay.nsite.lol): " NSYTE_RELAYS_INPUT
read -r -p "Blossom server URLs, comma-separated (for example https://cdn.hzrd149.com): " BLOSSOM_SERVER_URLS_INPUT
read -r -p "Optional named nsite (press enter for root npub site): " NSITE_NAME

normalize_list_secret() {
  printf '%s\n' "$1" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed '/^$/d'
}

if [[ "$NBUNK_SECRET" != nbunksec1* ]]; then
  echo "NBUNK_SECRET must be the nbunksec1... credential generated by 'nsyte ci'."
  exit 1
fi

NSYTE_RELAYS="$(normalize_list_secret "$NSYTE_RELAYS_INPUT")"
BLOSSOM_SERVER_URLS="$(normalize_list_secret "$BLOSSOM_SERVER_URLS_INPUT")"

if [[ -z "$NSYTE_RELAYS" ]]; then
  echo "NSYTE_RELAYS must include at least one relay URL."
  exit 1
fi

if [[ -z "$BLOSSOM_SERVER_URLS" ]]; then
  echo "BLOSSOM_SERVER_URLS must include at least one Blossom server URL."
  exit 1
fi

gh secret set NBUNK_SECRET --body "$NBUNK_SECRET"
gh secret set NSYTE_RELAYS --body "$NSYTE_RELAYS"
gh secret set BLOSSOM_SERVER_URLS --body "$BLOSSOM_SERVER_URLS"

if [[ -n "$NSITE_NAME" ]]; then
  gh secret set NSITE_NAME --body "$NSITE_NAME"
fi

echo "Repository secrets are configured for .github/workflows/deploy-nsite.yml"
